# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Mulberry
email: mulberry@wh-bremerhaven.de

description: > # this means to ignore newlines until "baseurl:"
  Mitten in Downtown Manhattan liegt die Mulberry Street, eine der ältesten Straßen New Yorks. Sie ist geprägt durch das Quartier Little Italy im Norden und Chinatown im Süden. Kaum ein anderer Ort steht mehr für das Zusammenleben unterschiedlicher Kulturen und die Vielfalt der Speisen wie die Mulberry Street. MULBERRY ST, das Restaurant im THE LIBERTY wird ab 10. März 2018 in seinen Menus diese Vielfalt leben. Kulinarische Kompositionen, ländlich, mediterran mit asiatischen Nuancen: Freuen Sie sich darauf.

description-eng: > # this means to ignore newlines until "baseurl:"
  Direct on the emigration quay, the 'Mulberry Street' restaurant pampers guests with an ample breakfast buffet, as well as refined and fine New York-style cuisine.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.mulberry-bremerhaven.de" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - octopress-autoprefixer
  
exclude:
  - Gemfile
  - Gemfile.lock
  
sass:
  sass_dir: assets/stylesheets
  style: :compressed